"""Rendering, comparison, deployment, audit, and diagnostics."""

from __future__ import annotations

import difflib
import hashlib
import json
import os
import shutil
import tempfile
import urllib.error
import urllib.request
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from .config import (
    WorkflowError,
    expand_path,
    load_target,
    load_yaml,
    runtime_environment,
    safe_relative,
    validate_repository,
)


RENDER_MARKER = ".workflow-render-root"
RENDER_MANIFEST = ".workflow-manifest.json"


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _prepare_output(path: Path, root: Path) -> None:
    path = path.resolve()
    if path in {Path("/").resolve(), root.resolve(), Path.home().resolve()}:
        raise WorkflowError(f"refusing unsafe render output: {path}")
    if path.exists():
        marker = path / RENDER_MARKER
        if not marker.is_file() and any(path.iterdir()):
            raise WorkflowError(f"refusing to replace unmarked non-empty output directory: {path}")
        shutil.rmtree(path)
    path.mkdir(parents=True)
    (path / RENDER_MARKER).write_text("generated by workflowctl\n", encoding="utf-8")


def _artifact_files(source: Path) -> list[tuple[Path, Path]]:
    if source.is_symlink():
        raise WorkflowError(f"artifact source may not be a symlink: {source}")
    if source.is_file():
        return [(source, Path("."))]
    if source.is_dir():
        files: list[tuple[Path, Path]] = []
        for path in sorted(source.rglob("*")):
            if path.is_symlink():
                raise WorkflowError(f"artifact tree may not contain a symlink: {path}")
            if path.is_file():
                files.append((path, path.relative_to(source)))
        return files
    raise WorkflowError(f"artifact source does not exist: {source}")


def render_target(root: Path, target_id: str, output: Path | None = None) -> dict[str, Any]:
    """Render all enabled target artifacts into a deterministic staging tree."""
    root = root.resolve()
    validate_repository(root)
    target = load_target(root, target_id)
    if output is None:
        configured = target["deployment"].get("bundle_output")
        output = root / configured if configured else root / ".build" / target_id
    output = output.resolve()
    _prepare_output(output, root)

    entries: list[dict[str, str]] = []
    rendered_paths: set[Path] = set()
    for selected in target["adapters"]:
        if not selected["enabled"]:
            continue
        adapter = load_yaml(root / selected["id"] / "deploy.yaml")
        for artifact in adapter["artifacts"]:
            source = (root / artifact["source"]).resolve()
            destination = safe_relative(
                artifact["destination"], f"{adapter['id']} artifact destination"
            )
            source_is_file = source.is_file()
            for source_file, source_relative in _artifact_files(source):
                relative = destination if source_is_file else destination / source_relative
                relative = Path() if relative == Path(".") else relative
                staged = output / adapter["id"] / relative
                if staged in rendered_paths:
                    raise WorkflowError(f"render collision for {adapter['id']}/{relative}")
                rendered_paths.add(staged)
                staged.parent.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(source_file, staged)
                entries.append(
                    {
                        "adapter": adapter["id"],
                        "source": str(source_file.relative_to(root)),
                        "relative_destination": str(relative),
                        "staged": str(staged.relative_to(output)),
                        "sha256": sha256(staged),
                    }
                )

    manifest: dict[str, Any] = {
        "schema_version": 1,
        "target": target_id,
        "kind": target["kind"],
        "files": sorted(entries, key=lambda item: (item["adapter"], item["relative_destination"])),
    }
    (output / RENDER_MANIFEST).write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    manifest["output"] = str(output)
    return manifest


def _destination_roots(target: dict[str, Any], env: dict[str, str]) -> dict[str, Path]:
    return {
        selected["id"]: expand_path(selected["destination"], env).resolve()
        for selected in target["adapters"]
        if selected["enabled"] and not selected["destination"].startswith("bundle://")
    }


def compare_target(
    root: Path, target_id: str, home: Path | None = None, output: Path | None = None
) -> tuple[dict[str, Any], list[dict[str, str]]]:
    """Render and compare a target with its configured destinations."""
    manifest = render_target(root, target_id, output)
    target = load_target(root, target_id)
    if target["kind"] == "bundle":
        return manifest, []
    env = runtime_environment(home)
    destinations = _destination_roots(target, env)
    stage = Path(manifest["output"])
    changes: list[dict[str, str]] = []
    for entry in manifest["files"]:
        destination = destinations[entry["adapter"]] / entry["relative_destination"]
        if not destination.exists() and not destination.is_symlink():
            status = "create"
        elif destination.is_file() and not destination.is_symlink() and sha256(destination) == entry["sha256"]:
            status = "unchanged"
        else:
            status = "update"
        change = {
            "status": status,
            "adapter": entry["adapter"],
            "destination": str(destination),
            "staged": str(stage / entry["staged"]),
        }
        changes.append(change)
    return manifest, changes


def unified_diff(change: dict[str, str]) -> str:
    """Return a text diff when both sides are UTF-8 text."""
    destination = Path(change["destination"])
    staged = Path(change["staged"])
    if change["status"] == "unchanged":
        return ""
    try:
        before = destination.read_text(encoding="utf-8").splitlines(keepends=True) if destination.is_file() else []
        after = staged.read_text(encoding="utf-8").splitlines(keepends=True)
    except UnicodeDecodeError:
        return ""
    return "".join(
        difflib.unified_diff(before, after, fromfile=str(destination), tofile=str(staged))
    )


def _atomic_copy(source: Path, destination: Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(dir=destination.parent, delete=False) as handle:
        temporary = Path(handle.name)
        with source.open("rb") as incoming:
            shutil.copyfileobj(incoming, handle)
    shutil.copymode(source, temporary)
    os.replace(temporary, destination)


def deploy_target(
    root: Path,
    target_id: str,
    home: Path | None = None,
    output: Path | None = None,
    dry_run: bool = False,
    mode: str | None = None,
) -> dict[str, Any]:
    """Deploy a target after rendering and comparison."""
    manifest, changes = compare_target(root, target_id, home, output)
    target = load_target(root, target_id)
    if target["kind"] == "bundle":
        return {"target": target_id, "kind": "bundle", "output": manifest["output"], "changes": []}
    if dry_run:
        return {"target": target_id, "kind": "dry-run", "output": manifest["output"], "changes": changes}

    install_mode = mode or target["deployment"]["mode"]
    if install_mode not in {"copy", "symlink"}:
        raise WorkflowError(f"unsupported deployment mode: {install_mode}")
    env = runtime_environment(home)
    backup_root = expand_path(target["deployment"]["backup_root"], env).resolve()
    state_root = expand_path(target["deployment"]["state_root"], env).resolve()
    timestamp = datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")
    installed: list[dict[str, str]] = []

    for change in changes:
        if change["status"] == "unchanged":
            continue
        destination = Path(change["destination"])
        staged = Path(change["staged"])
        if destination.exists() and destination.is_dir() and not destination.is_symlink():
            raise WorkflowError(f"refusing to replace directory with file: {destination}")
        if destination.exists() or destination.is_symlink():
            relative = destination.relative_to(_destination_roots(target, env)[change["adapter"]])
            backup = backup_root / timestamp / change["adapter"] / relative
            backup.parent.mkdir(parents=True, exist_ok=True)
            if destination.is_symlink():
                backup.symlink_to(os.readlink(destination))
                destination.unlink()
            else:
                shutil.copy2(destination, backup)
        destination.parent.mkdir(parents=True, exist_ok=True)
        if install_mode == "copy":
            _atomic_copy(staged, destination)
        else:
            if destination.exists() or destination.is_symlink():
                destination.unlink()
            destination.symlink_to(staged)
        installed.append(
            {
                "adapter": change["adapter"],
                "destination": str(destination),
                "sha256": sha256(staged),
                "mode": install_mode,
            }
        )

    state_root.mkdir(parents=True, exist_ok=True)
    state = {
        "schema_version": 1,
        "target": target_id,
        "deployed_at": datetime.now(UTC).isoformat(),
        "render_output": manifest["output"],
        "files": [
            {
                "adapter": entry["adapter"],
                "destination": str(
                    _destination_roots(target, env)[entry["adapter"]]
                    / entry["relative_destination"]
                ),
                "sha256": entry["sha256"],
                "mode": install_mode,
            }
            for entry in manifest["files"]
        ],
    }
    state_path = state_root / f"{target_id}.json"
    state_path.write_text(json.dumps(state, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return {
        "target": target_id,
        "kind": "deployment",
        "output": manifest["output"],
        "installed": installed,
        "state": str(state_path),
    }


def audit_target(root: Path, target_id: str, home: Path | None = None) -> list[dict[str, str]]:
    """Compare deployed files against the last deployment state manifest."""
    target = load_target(root, target_id)
    env = runtime_environment(home)
    state_path = expand_path(target["deployment"]["state_root"], env) / f"{target_id}.json"
    if not state_path.is_file():
        raise WorkflowError(f"no deployment state for {target_id}: {state_path}")
    state = json.loads(state_path.read_text(encoding="utf-8"))
    results: list[dict[str, str]] = []
    for entry in state["files"]:
        path = Path(entry["destination"])
        if not path.exists() and not path.is_symlink():
            status = "missing"
        elif path.is_symlink() and not path.exists():
            status = "broken-symlink"
        elif path.is_file() and sha256(path) == entry["sha256"]:
            status = "clean"
        else:
            status = "drifted"
        results.append({"status": status, "adapter": entry["adapter"], "destination": str(path)})
    return results


def inventory(root: Path) -> dict[str, list[str]]:
    """Return stable IDs from the repository registries."""
    validate_repository(root)
    return {
        "targets": [path.stem for path in sorted((root / "targets").glob("*.yaml"))],
        "sources": [item["id"] for item in load_yaml(root / "manifests/sources.yaml")["sources"]],
        "content": [item["id"] for item in load_yaml(root / "manifests/content.yaml")["artifacts"]],
        "services": [item["id"] for item in load_yaml(root / "services/registry.yaml")["services"]],
        "mcp_servers": [item["id"] for item in load_yaml(root / "services/mcp/registry.yaml")["servers"]],
        "adapters": [load_yaml(path)["id"] for path in sorted(root.glob("*/deploy.yaml"))],
    }


def doctor(root: Path, target_id: str, home: Path | None = None, network: bool = False) -> list[dict[str, str]]:
    """Check schemas, local commands, destinations, and optional public health endpoints."""
    validate_repository(root)
    target = load_target(root, target_id)
    env = runtime_environment(home)
    results: list[dict[str, str]] = []
    commands = {"opencode": "opencode", "codex": "codex", "claude": "claude", "grok": "grok"}
    for selected in target["adapters"]:
        if not selected["enabled"]:
            continue
        command = commands.get(selected["id"])
        if command:
            results.append(
                {
                    "status": "ok" if shutil.which(command) else "missing",
                    "check": f"command:{command}",
                    "detail": shutil.which(command) or "not found in PATH",
                }
            )
        if not selected["destination"].startswith("bundle://"):
            destination = expand_path(selected["destination"], env)
            results.append(
                {
                    "status": "ok" if destination.exists() else "not-created",
                    "check": f"destination:{selected['id']}",
                    "detail": str(destination),
                }
            )

    if network:
        for service in load_yaml(root / "services/registry.yaml")["services"]:
            health = service.get("healthcheck")
            if not health:
                continue
            if health.get("secret_ref"):
                results.append(
                    {
                        "status": "skipped-auth",
                        "check": f"service:{service['id']}",
                        "detail": "health check requires a secret reference",
                    }
                )
                continue
            url = service["endpoint"]["url"].rstrip("/") + health["path"]
            request = urllib.request.Request(url, method=health["method"])
            try:
                with urllib.request.urlopen(request, timeout=3) as response:
                    status = "ok" if response.status < 500 else "unhealthy"
                    detail = f"HTTP {response.status}"
            except (urllib.error.URLError, TimeoutError, OSError) as exc:
                status = "unreachable"
                detail = str(exc.reason) if isinstance(exc, urllib.error.URLError) else str(exc)
            results.append({"status": status, "check": f"service:{service['id']}", "detail": detail})
    return results
